services:
- type: web
  name: Abro-Md
  runtime: node
  repo: https://github.com/Temitopeareo/ABRO-MDB
  plan: free
  region: oregon
  buildCommand: npm install
  startCommand: npm start
  autoDeploy: false
version: "1"
